---
output: 
  pdf_document:
    latex_engine: xelatex
bibliography: references.bib
mainfont: Open Sans Regular
font size: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Box 1. Estimating covarying population trends of interacting species

Population trends are one of the key metrics to assess biodiversity change, informing decisions at the global level. Because biodiversity change is largely viewed as an accumulation of individual species' responses to a changing environment, population trends are often estimated under the unspoken assumption that they are responding independently to their environment. This approach ignores that populations co-occurring in space can covary in direct response to the environmental change, or indirectly due to the way environmental change alters their interactions with other species [@walter2017]. This covariation can be positive, where population dynamics become **synchronous** or positively correlated through time. Negative covariation occurs when population dynamics become **asynchronous**, meaning growth in one population coincides with declines in another.

A classic example of covarying populations are the Canadian lynx (*Lynx canadensis*), which fluctuates depending on its prey (*Lepus americanus*) ([Figure 1](#timeseries)).

![**Time series of snowshoe hare (*Lepus americanus*) and Canadian lynx (*Lynx canadensis*) populations in south-central Yukon between 1987 and 1994, from @mowat2003.** These populations covary positively through time as a result of their strong predator-prey relationship. **(a)** Population abundance time series. **(b)** Time series of annual growth rates, calculated from the abundance time series as $N_t/N_{t-1}$ , where $N$ is the population's abundance at time $t$ ($log_{10}$ transformed).](images/box1_ts_web-01.png){#timeseries}

We use two approaches to measure the overall population trend in this community: **(1)** an aggregated mean from single-population models as in the Living Planet Index, and **(2)** a hierarchical model which estimates a global trend among the two populations and individual trends for each population at once [@pedersen2019]. In the first approach, we fit a generalized additive model (GAM) to each population's growth rate through time, and average the models' predictions to obtain an overall trend. In the second, we fit a hierarchical GAM to all population trends at once, which allows individual populations' growth rates to vary in their own way, while estimating an overall trend that represents the common trend across populations.

The two approaches estimate similar trends ([**Figure 2a**](#compare)), with some minor differences. The hierarchical approach achieves a slightly more precise estimation of the overall trend ([**Figure 2b**](#compare)) with slightly more accuracy ([**Figure 2c**](#compare)). Importantly, the hierarchical approach also offers greater "under the hood" detail about how these populations are covarying, and how this might be influencing the uncertainty in the overall trend. By explicitly treating the covariation of interacting populations in our hierarchical model, we can access the variance-covariance matrix describing how the estimated coefficients of change covary through time between populations ([**Figure 3**](#vcov)).

![**Comparison of the aggregated mean GAM and hierarchical GAM approaches. (a)** Estimated overall trend obtained from each approach, compared to the expended mean growth rate (dotted line). **(b)** Comparison of the GAM and HGAM's precision in, measured as the width of the confidence intervals obtained from the standard error of the model(s). **(c)** Comparison of the GAM and HGAM's accuracy, measured as the difference between the predicted and expected growth rate for each model $(predicted - expected)$.](images/box1_compare_all_results.png){#compare width="635"}

![**A subset of the hierarchical GAM's variance-covariance matrix.** The color scale describes the correlation in the variance of each smoother coefficient estimated for each population at several time points throughout the time series of their growth rates. Highly positive covariance (dark blue) means the populations' growth rates were varying synchronously, while highly negative covariance (dark red) means the populations' growth rates were varying asynchronously at the given time point. Low values (white) indicate the growth rates were varying independently.](images/box1_covariance_smoothersperpopulation.png){#vcov width="629"}

### References

::: {#refs}
:::
