---
title: checking the scenarios
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 9)

# libraries
require(kableExtra)
require(ggplot2)
require(patchwork)
require(dplyr)
require(tidyselect)

# chunk params
knitr::opts_chunk$set(echo = FALSE, 
                      warning=FALSE, 
                      message=FALSE,
                      fig.height = 3)

# set ggplot theme
theme_set(theme_linedraw())
format_lpiplots <- list(
  theme(legend.position = "none"),
  labs(x = "", y = "LPI"),
  scale_x_continuous(breaks = seq(from = 0, to = 10, by = 2)))

# load results
df <- readRDS("~/Documents/GitHub/LPI-sensitivity/outputs/all_results.RDS")
```


```{r, fig.height=9}
ggplot(filter(df, Lag == "0")) +
  geom_line(aes(x = time, y = LPI_true, group = scenario), lty = 2, col = "grey") +
  geom_line(aes(x = time, y = LPI_boot, group = scenario, col = direction)) +
  facet_grid(interaction~Process_error, labeller = label_both) +
  labs(title = "lag = 0") + format_lpiplots
```

```{r, fig.height=9}
ggplot(filter(df, Lag == "1")) +
    geom_line(aes(x = time, y = LPI_true, group = scenario), lty = 2, col = "grey") +
  geom_line(aes(x = time, y = LPI_boot, group = scenario, col = direction)) +
  facet_grid(interaction~Process_error, labeller = label_both) +
  labs(title = "lag = 1")+ format_lpiplots
```

```{r, fig.height=9}
ggplot(filter(df, Lag == "2")) +
    geom_line(aes(x = time, y = LPI_true, group = scenario), lty = 2, col = "grey") +
  geom_line(aes(x = time, y = LPI_boot, group = scenario, col = direction)) +
  facet_grid(interaction~Process_error, labeller = label_both) +
  labs(title = "lag = 2")+ format_lpiplots
```

